### ISSUE TITLE
Tests Fail

### ISSUE THREAD

**Issue by loic-a** [p201-sp2016/NestedSampling_DMD#12]
running the tests results in the following error:
OSError: File b'example_data.txt' does not exist

There error arises from the fact that the tests are looking for the data in the main directory. If I manually move the data to there, then the tests successfully complete.

**Comment by vnmanoharan** [comment]
Tests fail for me too, after the latest commit.  It's always good practice to run the tests _before_ you commit, and to only commit (or merge) after the tests pass.

**Comment by JunYinDM** [comment]
thanks dear Prof.Manoharan,


But the testcode doesn’t fail to run on my side … it was actually also ran successfully before when the name was the textdmdcode.py, the wrong one. 
I am a bit confused … do you know what should we do to improve the code testing …


thanks

**Comment by vnmanoharan** [comment]
I run `nosetests -v` from the root directory of your repository (the directory _above_ the package directory). Here is the error message:

```
test_io (nsdmd.testdmdcode.TestFunctions) ... ERROR
test_model_NFW (nsdmd.testdmdcode.TestFunctions) ... ok
test_prior_transform_NFW (nsdmd.testdmdcode.TestFunctions) ... ERROR

======================================================================
ERROR: test_io (nsdmd.testdmdcode.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vnm\Documents\GitHub\p201\NestedSampling_DMD\nsdmd\testdmdcode.py", line 13, in test_io
    testdata_x,testdata_xerr,testdata_y,testdata_yerr = dmdio.load_data(filename)
  File "C:\Users\vnm\Documents\GitHub\p201\NestedSampling_DMD\nsdmd\dmdio.py", line 21, in load_data
    df =pd.read_csv(data_file)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas\parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas\parser.c:4184)
  File "pandas\parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas\parser.c:8449)
FileNotFoundError: File b'example_data.txt' does not exist

======================================================================
ERROR: test_prior_transform_NFW (nsdmd.testdmdcode.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vnm\Documents\GitHub\p201\NestedSampling_DMD\nsdmd\testdmdcode.py", line 19, in test_prior_transform_NFW
    testdata = dmdio.load_data('example_data.txt')
  File "C:\Users\vnm\Documents\GitHub\p201\NestedSampling_DMD\nsdmd\dmdio.py", line 21, in load_data
    df =pd.read_csv(data_file)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas\parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas\parser.c:4184)
  File "pandas\parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas\parser.c:8449)
FileNotFoundError: File b'example_data.txt' does not exist

----------------------------------------------------------------------
Ran 3 tests in 0.683s
```

**Comment by vnmanoharan** [comment]
If you structure your package and test data exactly as in the example package, it should work.

**Comment by dga471** [comment]
I encountered an issue like this before with our code. The solution (and I verified that it works for your package as well) is to put example_data.txt in the root level directory instead of in the same folder as the tests script. Not sure why this works.

**Comment by JunYinDM** [comment]
thanks Daniel!
It's very helpful!
